#! /bin/sh

# =========
# Autostart
# =========

# Authentication Agent
if [ -f /usr/lib/xfce-polkit/xfce-polkit ]; then
  killall xfce-polkit
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# USB/Multimedia Devices
if hash udiskie > /dev/null 2>&1 ; then
  killall udiskie
  udiskie --tray &
fi

# Starting polybar
killall -q polybar
#polybar topbar -r &
polybar -r topbar 2>/home/kelly/poly.log &

# Start Keybinds
killall sxhkd
sxhkd &

# Set Wallpaper
feh --bg-fill $WALLPAPER

# ==========
# Colors
# ==========
bspc config focused_border_color "$(xrdb -query | grep 'color4:'| awk '{print $NF}')"
bspc config normal_border_color "$(xrdb -query | grep 'color0:'| awk '{print $NF}')"
bspc config active_border_color "$(xrdb -query | grep 'color5:'| awk '{print $NF}')"
bspc config presel_feedback_color "$(xrdb -query | grep 'color2:'| awk '{print $NF}')"

# ==========
# Workspaces
# ==========
bspc monitor -d Main Code Web Media Social Design Work
bspc config focus_follows_pointer true

# =====
# Tiled
# =====
# Border width
bspc config border_width 1

# Gap between windows
bspc config window_gap 10
# bspc config top_padding           0
# bspc config right_padding         0
# bspc config bottom_padding        0
# bspc config left_padding          0


# Windows split ratio
bspc config split_ratio 0.5

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle false

# ============
# Window Rules-> Find WM_Class with
# xprop | grep WM_CLASS | awk '{print $4}'
# ============
bspc rule -r *:*
bspc rule --add Pamac-manager state=floating
bspc rule --add Pavucontrol state=floating
bspc rule --add yad state=floating
bspc rule --add Zathura state=tiled

# Desktop 1: Main
bspc rule --add libreoffice-*   desktop='^1' follow=on focus=on
bspc rule --add [Vv]mrc         desktop='^1' follow=on focus=on

# Desktop 2: Code
bspc rule --add atom            desktop='^2' follow=on focus=on
bspc rule --add code-oss        desktop='^2' follow=on focus=on
bspc rule --add gedit           desktop='^2' follow=on focus=on

# Desktop 3: Web
bspc rule --add Chromium-*      desktop='^3' follow=on focus=on

# Desktop 4: Media Spotify has a blank WM_Class btw
bspc rule --add [Ss]potify      desktop='^4' follow=on focus=on state=fullscreen

# Desktop 5: Chat
bspc rule --add Caprine         desktop='^5' follow=on focus=on
bspc rule --add Mattermost      desktop='^5' follow=on
bspc rule --add Pidgin          desktop='^5' follow=on state=floating

# Desktop 6: Design
bspc rule --add Darktable       desktop="^6"
bspc rule --add Gimp            desktop="^6"
bspc rule --add gimp            desktop="^6"
bspc rule --add Inkscape        desktop="^6"
bspc rule --add Rawtherapee     desktop="^6"
bspc rule --add Shotwell        desktop="^6"

# Desktop 7: Work
bspc rule --add firefox         desktop='^7' follow=on focus=on #Webmail


# vim:filetype=sh
