#! /bin/sh

##############################################
# Required Auto-Start Applications
##############################################

# Authentication Agent
if [ -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ] ; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# USB/Multimedia Devices
if hash udiskie > /dev/null 2>&1 ; then
    udiskie &
fi

# Lockscreen loading on inactivity
xautolock -detectsleep -time 5 -locker "betterlockscreen --lock blur" -killtime 15 -killer "systemctl suspend" &

# Autostart some apps
numlockx &
sxhkd   &
feh --bg-fill ~/.wallpapers/background.png
picom -f --config ~/.config/picom.conf &
nm-applet &

# Starting the bar
killall polybar
polybar topbar -r &
$HOME/.config/polybar/scripts/spotify/spotify_status.py &

##############################################
# Visual Options
##############################################
# Monitor Names
bspc monitor -d Main Code Web Media Social Design

# Decoration Stuff ##

# Gaps and borders
bspc config border_width          3
bspc config window_gap            15
bspc config borderless_monocle    true
bspc config gapless_monocle       false


# Funcionality
bspc config focus_follows_pointer true
bspc config split_ratio           0.5

##############################################
# Rules -> Find WM_Class with
# xprop | grep WM_CLASS | awk '{print $4}'
##############################################
bspc rule -r *:*
bspc rule -a Pamac-manager state=floating

#Desktop 1: Main
bspc rule -a libreoffice-* desktop='^1' follow=on focus=on

#Desktop 2: Code
bspc rule -a atom desktop='^2' follow=on focus=on
bspc rule -a code-oss desktop='^2' follow=on focus=on

#Desktop 3: Web
bspc rule -a Chromium-* desktop='^3' follow=on focus=on

#Desktop 4: Media
bspc rule -a Spotify desktop='^4' follow=on focus=on

#Desktop 5: Chat
bspc rule -a Caprine desktop='^5' follow=on focus=on
bspc rule -a Mattermost desktop='^5' follow=on

# bspc rule -a URxvt   state=floating center=true rectangle=800x600+0+0
bspc rule -a Zathura state=tiled

# vim:filetype=sh
bash "$HOME/.config/bspwm/bspwm_colors.sh" &
