#! /bin/sh

# =========
# Autostart
# =========
# Authentication Agent
if [ -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 ] ; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# USB/Multimedia Devices
if hash udiskie > /dev/null 2>&1 ; then
    udiskie &
fi

# Lockscreen loading on inactivity
xautolock -detectsleep -time 5 -locker "betterlockscreen --lock blur" -killtime 15 -killer "systemctl suspend" &

# Enable Numlock
numlockx &

# Start Keybinds
sxhkd &

# Set Wallpaper
feh --bg-fill $WALLPAPER

# Start Compositor
picom -f --config ~/.config/picom.conf &

# Start Network Manager Applet for tray
nm-applet &

#setxkbmap -layout us -variant euro
setxkbmap -layout us -variant altgr-intl

# Starting polybar
killall polybar
polybar topbar -r &

# ==========
# Workspaces
# ==========
bspc monitor -d Main Code Web Media Social Design
bspc config focus_follows_pointer true

# =====
# Tiled
# =====
# Border width
bspc config border_width 3

# Gap between windows
bspc config window_gap 10

# Windows split ratio
bspc config split_ratio 0.5

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle true

# ============
# Window Rules-> Find WM_Class with
# xprop | grep WM_CLASS | awk '{print $4}'
# ============
bspc rule -r *:*
bspc rule --add Pamac-manager state=floating
bspc rule --add yad state=floating
bspc rule --add Zathura state=tiled

# Desktop 1: Main
bspc rule -a libreoffice-*  desktop='^1' follow=on focus=on

# Desktop 2: Code
bspc rule -a atom           desktop='^2' follow=on focus=on
bspc rule -a code-oss       desktop='^2' follow=on focus=on

# Desktop 3: Web
bspc rule -a Chromium-*   desktop='^3' follow=on focus=on

# Desktop 4: Media
bspc rule -a Spotify      desktop='^4' follow=on focus=on

# Desktop 5: Chat
bspc rule -a Caprine      desktop='^5' follow=on focus=on
bspc rule -a Mattermost   desktop='^5' follow=on
bspc rule -a firefox      desktop='^5' follow=on focus=on #Used for Webex at work

# Desktop 6: Design
bspc rule -a Darktable     desktop="^4"
bspc rule -a Gimp          desktop="^4"
bspc rule -a gimp          desktop="^4"
bspc rule -a Inkscape      desktop="^4"
bspc rule -a Rawtherapee   desktop="^4"
bspc rule -a Digikam       desktop="^4"
bspc rule -a Shotwell       desktop="^4"

# vim:filetype=sh
bash "$HOME/.config/bspwm/bspwm_colors.sh" &
