format = "[ﮂ ](cyan)$directory$git_branch$git_commit$git_status$character"
# Don't print a new line at the start of the prompt
add_newline = true

[directory]
style = "blue"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[●](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[●](red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = true
